### ISSUE TITLE
argStyleText is not supported

### ISSUE THREAD

**Issue by nkovacs** [messageformat/parser#1]
The second string is valid [according to ICU](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html), but can't be parsed by messageformat-parser:

```
var parse = require('messageformat-parser').parse;

console.log(parse("{0,date,long}"));
console.log(parse("{0,date,y-M-d HH:mm:ss zzzz}"));
```

I know messageformat.js doesn't support the second one, but [I'm using only the parser for globalize.js](https://github.com/globalizejs/globalize/pull/653), which would be able to support the second one.

**Comment by nkovacs** [comment]
This is also valid in ICU:

```
{var,date,y-M-d,HH:mm:ss,zzzz}
```

In this case, argStyle should be `y-M-d,HH:mm:ss,zzzz` (there can only be one argStyle), but messageformat-parser instead parses it as three separate arguments.

**Comment by eemeli** [comment]
Re-opening this, because tbh we should drop the current default `.split(',').trim()` processing, and assume that the current `strictFunctionParams` is always true. That would make us more spec-compliant, let us get rid of an option, and make issues like messageformat/messageformat.js#185 much easier to solve. It should be up to the called function to handle the string input it receives.

One open question here is whether the output should be trimmed of white space. The spec is unclear on this. I think we should trim, as that would match what we're doing everywhere else as well.

**Comment by SlexAxton** [comment]
Agree on trim.

**Comment by eemeli** [comment]
I left the messageformat-parser output untrimmed for now, but added a trimmer in the messageformat compiler. This way if someone else wants to use the parser, they get to make up their own mind on this, but our formatters don't need to all trim their inputs separately.

**Comment by mhuebert** [comment]
Overall this change made my life easier, thanks!

One question; since the string is trimmed, is there a way to escape leading or trailing space characters to have them included? I don't see any mention of this in the formatting docs.

**Comment by SlexAxton** [comment]
Personally if leading/trailing space is significant, I add it outside of
the translated message since a translator will have no idea anyways.
